# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': '',
                'git_url': 'https://github.com/rkim1026/si2026-skydiver-rkim1026',
                'lib_path': 'skydiver'},
  'syms': { 'skydiver.cli': {},
            'skydiver.physics': { 'skydiver.physics.terminal_velocity': ('skydiver.html#terminal_velocity', 'skydiver/physics.py'),
                                  'skydiver.physics.time_to_fraction': ('skydiver.html#time_to_fraction', 'skydiver/physics.py'),
                                  'skydiver.physics.velocity_at_time': ('skydiver.html#velocity_at_time', 'skydiver/physics.py')}}}
